name: thesis-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.1.3
  - pandas=2.3.3
  - matplotlib=3.10.6
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - tensorflow=2.19.1
  - jupyterlab=4.4.9
  - ipykernel=7.0.1
  - openpyxl=3.1.5
  - pip
  - pip:
      - tqdm
      - tabulate
      - keras-tuner
